package com.example.ulaugh.utils

import android.Manifest

object Constants {
    const val TAG = "NOTESAPPTAG123"
    const val BASE_URL = "https://ulaugh.mlbranch.com/"
    const val USER_TOKEN = "user_token"
    const val USER_NAME = "user_name"
    const val FULL_NAME = "full_name"
    const val PHONE_NO = "phone_no"
    const val USER_DATA = "user_data"
    const val PROFILE_PIC = "profile_pic"
    const val POST_SHARE_REF = "postShare"
    const val ONLINE_USER_REF = "onlineUsers"
    const val REACTION = "reaction"
    const val IS_SEEN = "is_seen"
    const val IS_ONLINE = "is_online"
    const val REACTION_TYPE = "reaction_type"
    const val EMAIL = "email"
    const val IMAGE = "image"
    const val OTP = "otp"
    const val USERS_REF = "users"
    const val FRIENDS_REF = "friends"
    const val IS_PRIVATE = "is_private"
    const val IS_FOLLOW = "_follow"
    const val POST = "post"
    const val EMOTION_UPDATE = "emotion_update"
    const val POST_ID = "post_id"
    const val MESSAGE_TOKEN = "message_token"
    const val PROFILE = "profile"
    const val IS_CHECKED = "is_checked"
    const val EMOTIONS_DATA = "emotion"
    const val FOLLOW = "follow"
    const val REQUEST = "request"
    const val REACTED = "reacted"
    const val ACCEPT = "Accept"
    const val REJECTED = "Reject"
    const val NOTIFICATION = "notification"
    const val FIREBASE_ID = "firebase_id"
    const val PREFS_TOKEN_FILE = "prefs_token_file"
    const val FILENAME_FORMAT = "yyyy-MM-dd-HH-mm-ss-SSS"
    val REQUIRED_PERMISSIONS = arrayOf(Manifest.permission.CAMERA)
    const val REQUEST_CODE_PERMISSIONS = 20
    const val DATE_TIME = "date_time"
    const val DESCRIPTION = "description"
    const val IMAGE_URL = "image_url"
    const val TAGS_LIST = "tagsList"
    const val FIREBASE_BASE_URL = "https://fcm.googleapis.com"
    const val SERVER_KEY =
        "AAAAPdrY6ck:APA91bFCcbD-sWQti4SrmJ9GYK68WJ2_6WSHxZ7UFrHXhr9Sgg8DXnZUPJDMsQlRuRb33TObifRHGDwqCThSzjciQjDY2QRh9TmLsTnjxb8Ib9wRLX6L4K1P0Fc4R3YhvqOcUYx4ZG2A"
    const val CONTENT_TYPE = "application/json"
}